### ISSUE TITLE
Unification broken since  2.20.16

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#309]
[Item#45](http://www.complang.tuwien.ac.at/ulrich/trealla-prolog/Item#45)

**Comment by infradig** [comment]
The README has never mentioned rational trees, so I have updated it to
reflect that support is considered experimental only and thus not
officially supported. There is a flaw in the handling and after much
thought it is now for the *look-at-later* basket.

**Comment by infradig** [comment]
Well there you go, another hacky fix for rational trees. I know there's a
flaw just waiting for an example to be uncovered.

**Comment by UWN** [comment]
Originally (in the issues you deleted, see also [#1](5)) you said that you are committed to support rational trees. That's the only reason I am looking into this. Now it seems you changed.

However, I suspect that the very errors that occur in rational tree unification can also be found in regular NSTO term unification. The corresponding examples there are only more complex and thus need more compute to be discovered. For this reason I believe that identifying such cases will also be of advantage to the correctness of NSTO term unification.

**Comment by infradig** [comment]
The flaw I mentioned in rational tree unification may indeed lead to
problems in the general case (though I can't produce an example of it yet).
That's why it ideally needs to be disabled (shaves 2 secs off chess sample)
or rewritten (of which I have a better idea now how to do reasonably
efficiently). I'm leaning to the latter option.
