### ISSUE TITLE
TCO examples

### ISSUE THREAD

**Issue by infradig** [trealla-prolog/trealla#543]
```
$ cat w.pl
main(N) :- N > 0, N1 is N-1, main(N1).

$ cat v.pl
% No local vars & no structures, yet not recovered...

zx81(X, Y) :- Y is (X*75+74) mod 65537.
main(0) :- !.
main(I) :- zx81(I, _), I2 is I-1, main(I2).

$ cat y.pl
f(0) :- !, fail.
f(_).
main(N) :- f(N), N1 is N-1, main(N1).

$ cat z.pl
f(X) :- X > 0, X=Y.
main(N) :- f(N), N1 is N-1, main(N1).
```

All these examples run in constant memory with SWI Prolog:
```
$ time swipl -g 'main(100000000);halt' w.pl
```

With Trealla only v.pl does not.

**Comment by flexoron** [comment]
```
zx81(X,Y) :- Y is X*1.
main(0) :- !.
% main(I) :- zx81(I,I), I2 is I-1, main(I2). % Good
% main(I) :- zx81(I,M), I2 is I-1, main(I2). % Bad, Var M eats memory
% main(I) :- zx81(I,_), I2 is I-1, main(I2). % Bad, Var _ eats memory
```

**Comment by infradig** [comment]
Yes, it's the call to xz81/2 (when you get var/var unification)  that causes main/1 not to be TCO. I know why
just haven't worked out a solution that doesn't break another test, there
may be 2 things to fix.

**Comment by Jean-Luc-Picard-2021** [comment]
For WAM there proposals like Older and 
Rummel's incremental garbage collection algorithm
https://www.researchgate.net/publication/2751901

But especially for tail recursion, I think frame reuse
is key, SWI-Prolog does it by a special compilation.
You see it via vm_list/1, the i_depart/1 instruction:
```
?- vm_list(main/1).

       9 l_nolco('L1')
      11 l_var(0,1)
      14 i_tcall
L1:   15 b_var1
      16 i_depart(user:main/1)
      18 i_exit
```
Yet another approach is to not have frames at all.
I have done that in Dogelog Player, where predicates
suchs as DEC10 ancestor/1 or a back trace in an 

error is impossible by design.
