### ISSUE TITLE
Missing fact, impractical code

### ISSUE THREAD

**Issue by flexoron** [trealla-prolog/trealla#563]
v1.28.19
```
?- [user].
'[]'.
'[]' :- _ .
end_of_file.

?- listing.  
[]:-call(_).
   true.
?- 
```
Fact lost, Rule useless.

**Comment by UWN** [comment]
Is this really important? From a very formal viewpoint it is, but de facto this interferes with the built-in `(.)/2` (like `[user].`) and term expansion mechanisms. Both are so far not standardized because there are so many tiny differences in their definition for some and more fundamental reasons for others. It's a bit like `end_of_file.` which according to 13211-1 should be a fact, but you too assume that it is not. And if you really want to define it, use `end_of_file :- true.`.

Why this interferes with `[user].`: In many systems you can say `[tier1,tier2...].` to prepare all those files for execution. So `[]` for preparing none fits in. At least this is the case for SICStus, Quintus etc. I'd say call systems in a closer DEC10 descendance.

And the other interference is the meaning of `(.)/2` as principal functor in a Prolog text in many systems. Like SICStus:

```
| ?- [user].
% compiling user...
| [f(1),f(2),f(3)].
| 
% compiled user in module user, 305 msec 514624 bytes
yes
| ?- f(X).
X = 1 ? ;
X = 2 ? ;
X = 3 ? ;
no
```

**Comment by infradig** [comment]
Thanks, I had forgotten about those.

**Comment by flexoron** [comment]
v1.28.22
```
?- [user].
[].
"".

?- listing.
[].
[].
   true.
?-
```

**Comment by UWN** [comment]
Do not rely on it, should constraint extensions (`clpz`, `chr`) be included in Trealla, this will be gone.
