### ISSUE TITLE
Feature request indirect implementation of new built-ins

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [trealla-prolog/trealla#68]
It seems Trealla Prolog doesn't have getbit evaluable functions:
```
?- X is getbit(1024, 2).
   error(type_error(evaluable,getbit/2),(is)/2).
```
The same evaluable function is available in SWI-Prolog:

> **getbit(+IntExprV, +IntExprI)**
> https://www.swi-prolog.org/pldoc/doc_for?object=f(getbit/2)

See Markus Triska for some indirect implementation idea below.

**Comment by triska** [comment]
Instead of introducing a specialized function for this, what about **automatically&nbsp;detecting** such patterns, and *internally* compiling this to more efficient code? In this way, also existing programs would automatically improve without any changes to the program themselves, and application programmers would not have to learn a new arithmetic function, nor produce code that is not directly portable to other Prolog&nbsp;systems.

**Comment by Jean-Luc-Picard-2021** [comment]
Maybe you suggest that you would then only define this function
internall,y and not expose it to the end-user. 
There is nothing in this feature request that would forbid
detecting some patterns. But the pattern is not unique,

I already gave two patterns:
```
testbit(X, N) :- X /\ (1 << N) =\= 0.
% testbit(X, N) :- (X >> N) /\ 1 =\= 0.
```
How many patterns are there? Which one would you detect? 
Where and how do you document these patterns,
so that the application programmers go for it? The easiest
documentation is to introduce a predicate `testbit/2` or

an evaluable function `getbit/2`. Easily available in most
binint libraries. Probably the core reference for it would be:

> Function: **int mpz_tstbit (const mpz_t op, mp_bitcnt_t bit_index)**
> Test bit bit_index in op and return 0 or 1 accordingly.
> https://gmplib.org/manual/Integer-Logic-and-Bit-Fiddling

**Comment by triska** [comment]
I think detection and dedicated compilation of the following pattern would solve the issue:

<pre>
<i>Expr</i> <b>/\</b> (1 &lt;&lt; N)
</pre>

If this pattern occurs in any arithmetic expression, you do not need to explicitly compute `1 << N`: You can *internally* automatically use `mpz_tstbit` with argument `N` instead.

Instead of documenting `testbit/2`, you can document that **this pattern is automatically treated especially efficiently**.

**Comment by Jean-Luc-Picard-2021** [comment]
What about this expression:
```
(1 << N) /\ Expr 
```
If you want that N is computed before Expr. Because it has
some side effect. Evaluable expressions are not free of side
effects in practical Prolog. For example this here has a side effect:
```
?- X is random(100).
X = 21.
```
With an available testbit/1, since it is a predicate. You anyway
need to first manually compute the arguments. So you can choose:
```
P is N, Q is Expr, testbit(Q, P).
```
I am even not sure whether ISO core standard specifies the
evaluation order of compound evaluable expressions. Some 
programming languages explicitly specify it, like Java if I am 

not mistaken, and others¨ leave it to the compiler. You would 
need to do much more ground work, and write much more than
just mention a little pattern somewhere in the documentation.

**Comment by Jean-Luc-Picard-2021** [comment]
Anyway if you want from Trealla Prolog that it does
such pattern matching based optimizations you need to
open a new ticket. Its not in the scope of this ticket,

Since the ticket says "request evaluable function",
To stay in this ticket neverthless, I have renamed the
ticket now. So that you continue developing your 

ideas here. But the best would be anyway if the ticket
is transfered to Scryrer Prolog. So closing the ticket now.
